@startuml
/' Nord 主题配色'/
!define NORD_POLAR_NIGHT1 #2E3440
!define NORD_POLAR_NIGHT2 #3B4252
!define NORD_POLAR_NIGHT3 #434C5E
!define NORD_POLAR_NIGHT4 #4C566A

!define NORD_SNOW_STORM1 #D8DEE9
!define NORD_SNOW_STORM2 #E5E9F0
!define NORD_SNOW_STORM3 #ECEFF4

!define NORD_FROST1 #8FBCBB
!define NORD_FROST2 #88C0D0
!define NORD_FROST3 #81A1C1
!define NORD_FROST4 #5E81AC

!define NORD_AURORA1 #BF616A
!define NORD_AURORA2 #D08770
!define NORD_AURORA3 #EBCB8B
!define NORD_AURORA4 #A3BE8C
!define NORD_AURORA5 #B48EAD

!define GRPC_REQ #BF616A
!define HTTP_REQ #D08770
!define RETURN #005BEA

<style>

note {
/'border 边框颜色'/  LineColor NORD_AURORA3 
/'border 边框粗细'/  LineThickness 1
/'背景色'/           BackGroundColor NORD_AURORA3
}

actor {
/'线条粗细'/   LineThickness 2
/'线条色'/     LineColor NORD_FROST4
/'背景色'/     BackgroundColor NORD_SNOW_STORM3
}

</style>

scale 10
skinparam dpi 96
skinparam responseMessageBelowArrow true
skinparam Participant {
/'背景色'/     BackgroundColor NORD_FROST4
/'边框色'/     BorderColor NORD_FROST4
/'字体颜色'/   FontColor NORD_SNOW_STORM3
}


skinparam Sequence {
/'Box 背景色'/    BoxBackgroundColor NORD_SNOW_STORM1
/'Box 边框色'/    BoxBorderColor NORD_SNOW_STORM3

/'箭头颜色'/      ArrowColor GRPC_REQ
/'箭头线条粗细'/  ArrowThickness 2

/'分隔线背景色'/    DividerBackgroundColor NORD_POLAR_NIGHT4
/'分隔线边框色'/    DividerBorderColor #eee
/'分割线边框粗细'/  DividerBorderThickness 0
/'分隔线字体颜色'/  DividerFontColor NORD_SNOW_STORM3
}

skinparam database {
/'背景色'/     BackgroundColor NORD_FROST1
/'边框色'/     BorderColor NORD_POLAR_NIGHT4
/'字体颜色'/   FontColor NORD_POLAR_NIGHT1
/'字体大小'/   FontSize 10
}

@enduml
